<!--- 
	*****************************************************************************************
	Name:		rpt_pil_selection.cfm
	
	Function:	Project Information List Report.  User can selected which report to run.
				Reports are generated by selling company.
	History:	bj010802 - initial code
	
	*****************************************************************************************
--->
<html>
<head>
<title>Project Information List - Selection</title>
<LINK REL="stylesheet" HREF="stylePIL.css" TYPE="text/css">
</head>
<body style="margin: 0; page: doublepage; page-break-after: right">
<table cellspacing="1" cellpadding="1" border="0" width=450>
<tr valign="top">
	<td width=50>&nbsp;</td>
	<td colspan=2 class=tdheader><b>Project Information List - Selection</b></td>
</tr>
<tr>
	<td width=50>&nbsp;</td>
	<td colspan=2 class=highlight>Click the radio button next to the report you wish to run, then click the <b><i>Run Report</i></b> button, or click the <b><i>Cancel</i></b> button to return to the main page.</td>
</tr>
<tr><td colspan=3</td></tr></tr>
<form action="rpt_pil.cfm?no_menu=1" method="post" target="new">
<tr>
	<td width=50>&nbsp;</td>
    <td width=200 align=right><input type=radio name=select_rpt value="1"></td>
    <td width=200>C. Beck</td>
</tr>
<tr>
	<td width=50>&nbsp;</td>
    <td width=200 align=right><input type=radio name=select_rpt value="3"></td>
    <td width=200>Group Dynamics</td>
</tr>
<tr>
	<td width=50>&nbsp;</td>
    <td width=200 align=right><input type=radio name=select_rpt value="4"></td>
    <td width=200>Share-Com</td>
</tr>
<tr>
	<td width=50>&nbsp;</td>
    <td width=200 align=right><input type=radio name=select_rpt value="2"></td>
    <td width=200>Vista-Com</td>
</tr>
<tr>
	<td width=50>&nbsp;</td>
    <td width=200 align=right><input type=radio name=select_rpt value="5"></td>
    <td width=200>All Companies</td>
</tr>
<tr height=20><td colspan=3></td></tr>
<tr>
	<td width=50>&nbsp;</td>
    <td width=200 colspan=2 align=right>Select Report Type --</td>
</tr>
<tr>
	<td width=50>&nbsp;</td>
    <td width=200 align=right><input type=radio name=select_type value="1" checked></td>
    <td width=200>Display Only</td>
</tr>
<tr>
	<td width=50>&nbsp;</td>
    <td width=200 align=right><input type=radio name=select_type value="2"></td>
    <td width=200>Printable Format</td>
</tr>
<tr height=20><td colspan=3></td></tr>
<tr>
	<td width=50>&nbsp;</td>
	<TD ALIGN="Center"><INPUT  TYPE="submit" NAME="submit" VALUE="Run Report"></td>
		<form action="index.cfm" method="post">
	<td ALIGN="Center"><INPUT  TYPE="submit" NAME="cancel" VALUE="Cancel"></TD>
</TR>
<tr><td colspan=3</td></tr></tr>
</form>
</table>
</body>
</html>
